{{- if and .Values.secrets.mongodb.enabled (not .Values.secrets.mongodb.secretName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chatalgo-api.fullname" . }}-mongodb
  labels:
    {{- include "chatalgo-api.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-uri: {{ printf "mongodb+srv://%s:%s@chatalgo.e3jtoia.mongodb.net/" .Values.secrets.mongodb.username .Values.secrets.mongodb.password | b64enc | quote }}
{{- end }}

{{- if and .Values.secrets.openai.enabled (not .Values.secrets.openai.secretName) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chatalgo-api.fullname" . }}-openai
  labels:
    {{- include "chatalgo-api.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.secrets.openai.apiKey | b64enc | quote }}
{{- end }}
