spring:
  application:
    name: chatalgo-api
  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_URI}/
      database: ${MONGODB_DATABASE}
      auto-index-creation: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

logging:
  level:
    org.springframework.data.mongodb: DEBUG
