spring:
  application:
    name: chatalgo-api
  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_URI}/
      database: ${MONGODB_DATABASE}
      auto-index-creation: true
  ai:
    vertex:
      ai:
        gemini:
          project-id: ${GEMINI_PROJECT_ID}
          location: ${GEMINI_LOCATION}
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: ${CHAT_MODEL_NAME}
        base-url: ${CHAT_BASE_URL}
        completions-path: ${CHAT_COMPLETION_PATH}

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.springframework.ai: DEBUG

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: ${JWT_TOKEN_EXPIRED}
