apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deploy.fullname" . }}-app-config
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
type: Opaque
data:
  application.yml: {{ tpl (cat "spring:
  application:
    name: chatalgo-api
  data:
    mongodb:
      uri: mongodb+srv://{{ .Values.secrets.MONGODB_USERNAME }}:{{ .Values.secrets.MONGODB_PASSWORD }}@{{ .Values.secrets.MONGODB_URI }}/
      database: {{ .Values.secrets.MONGODB_DATABASE }}
      auto-index-creation: true
  ai:
    openai:
      api-key: {{ .Values.secrets.OPENAI_API_KEY }}

logging:
  level:
    org.springframework.data.mongodb: DEBUG") . | b64enc }}
