# Production environment values for chatalgo-api
# This file contains non-sensitive values for production environments

replicaCount: 2

image:
  repository: chatalgo-api
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: api.chatalgo.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: chatalgo-api-tls
      hosts:
        - api.chatalgo.com

resources:
  limits:
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 1000m
    memory: 1024Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - chatalgo-api
          topologyKey: kubernetes.io/hostname

application:
  name: chatalgo-api
  mongodb:
    database: chatalgo

# Environment variables
env:
  extra:
    - name: SPRING_PROFILES_ACTIVE
      value: "prod"
    - name: JAVA_OPTS
      value: "-Xmx1536m -Xms1024m -XX:+UseG1GC -XX:MaxGCPauseMillis=200"

# Configure ConfigMap
configMap:
  data:
    application-prod.yml: |-
      spring:
        data:
          mongodb:
            database: ${MONGODB_DATABASE}
        ai:
          openai:
            timeout: 30
        
      logging:
        level:
          org.springframework.data.mongodb: INFO
          lab.ujumeonji.chatalgoapi: INFO
        file:
          name: /var/log/chatalgo-api/application.log
        
      # Production specific settings
      server:
        tomcat:
          max-threads: 200
          min-spare-threads: 20
      
      management:
        endpoints:
          web:
            exposure:
              include: health,info,metrics
        endpoint:
          health:
            show-details: never
